// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniMercadoInteligente.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MiniMercadoInteligente.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260325133411_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MiniMercadoInteligente.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EstimatedLoss")
                        .HasColumnType("numeric");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AlertId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SessionId");

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("MiniMercadoInteligente.Domain.Entities.Area", b =>
                {
                    b.Property<Guid>("AreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CameraId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ConfidenceBase")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SensorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AreaId");

                    b.ToTable("areas", (string)null);
                });

            modelBuilder.Entity("MiniMercadoInteligente.Domain.Entities.CameraDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<string>("CameraId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("CondominiumId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEntryCamera")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsExitCamera")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("RtspUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Active");

                    b.HasIndex("AreaCode");

                    b.HasIndex("AreaId");

                    b.HasIndex("CameraId")
                        .IsUnique();

                    b.HasIndex("CondominiumId");

                    b.ToTable("camera_devices", (string)null);
                });

            modelBuilder.Entity("MiniMercadoInteligente.Domain.Entities.CartItem", b =>
                {
                    b.Property<Guid>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AreaCode")
                        .HasColumnType("text");

                    b.Property<string>("CameraId")
                        .HasColumnType("text");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("numeric");

                    b.Property<string>("EvidenceId")
                        .HasColumnType("text");

                    b.Property<bool>("IsReconciled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.Property<string>("SensorId")
                        .HasColumnType("text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("CartItemId");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("ProductId");

                    b.HasIndex("SessionId");

                    b.HasIndex("SessionId", "ProductId");

                    b.ToTable("cart_items", (string)null);
                });

            modelBuilder.Entity("MiniMercadoInteligente.Domain.Entities.DeviceApiKey", b =>
                {
                    b.Property<Guid>("DeviceApiKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DeviceApiKeyId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("DeviceId", "Active");

                    b.ToTable("device_api_keys", (string)null);
                });

            modelBuilder.Entity("MiniMercadoInteligente.Domain.Entities.EventRecord", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("EventId");

                    b.HasIndex("AreaId");

                    b.HasIndex("EventType");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("ProductId");

                    b.HasIndex("SessionId");

                    b.ToTable("event_records", (string)null);
                });

            modelBuilder.Entity("MiniMercadoInteligente.Domain.Entities.Gate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CondominiumId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GateId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsEntryGate")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsExitGate")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Active");

                    b.HasIndex("CondominiumId");

                    b.HasIndex("GateId")
                        .IsUnique();

                    b.ToTable("gates", (string)null);
                });

            modelBuilder.Entity("MiniMercadoInteligente.Domain.Entities.IdempotencyKey", b =>
                {
                    b.Property<Guid>("IdempotencyKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.HasKey("IdempotencyKeyId");

                    b.ToTable("idempotency_keys", (string)null);
                });

            modelBuilder.Entity("MiniMercadoInteligente.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("GatewayPayloadJson")
                        .HasColumnType("text");

                    b.Property<string>("GatewayRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsAutoCheckout")
                        .HasColumnType("boolean");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethodToken")
                        .HasColumnType("text");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("uuid");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TriggerSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PaymentId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("GatewayRef");

                    b.HasIndex("SessionId");

                    b.HasIndex("Status");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("MiniMercadoInteligente.Domain.Entities.PlanogramAreaProduct", b =>
                {
                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("ExpectedPosition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WeightToleranceGrams")
                        .HasColumnType("integer");

                    b.HasKey("AreaId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("planogram_area_products", (string)null);
                });

            modelBuilder.Entity("MiniMercadoInteligente.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("DetectionConfidenceThreshold")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsHighRisk")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSoldByUnit")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWeightControlled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("NominalWeightGrams")
                        .HasColumnType("integer");

                    b.Property<string>("QrCode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("UnitWeightGrams")
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("VisionLabel")
                        .HasColumnType("text");

                    b.Property<int>("WeightToleranceGrams")
                        .HasColumnType("integer");

                    b.HasKey("ProductId");

                    b.HasIndex("Active");

                    b.HasIndex("Barcode");

                    b.HasIndex("IsWeightControlled");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("MiniMercadoInteligente.Domain.Entities.ProductPrice", b =>
                {
                    b.Property<Guid>("ProductPriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("ProductPriceId");

                    b.HasIndex("ProductId");

                    b.ToTable("product_prices", (string)null);
                });

            modelBuilder.Entity("MiniMercadoInteligente.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActiveTrackId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("AutoCheckoutAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("AutoCheckoutTriggered")
                        .HasColumnType("boolean");

                    b.Property<string>("BlockReason")
                        .HasColumnType("text");

                    b.Property<Guid>("CondominiumId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentAreaCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DefaultPaymentMethodSnapshot")
                        .HasColumnType("text");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EnteredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntryGateId")
                        .HasColumnType("text");

                    b.Property<string>("EntryMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExitGateId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExitedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FraudFlagsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("FraudScore")
                        .HasColumnType("integer");

                    b.Property<bool>("FraudSuspected")
                        .HasColumnType("boolean");

                    b.Property<string>("ReconciliationVersion")
                        .HasColumnType("text");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TrackingConfidence")
                        .HasColumnType("numeric");

                    b.Property<bool>("TrackingLocked")
                        .HasColumnType("boolean");

                    b.HasKey("SessionId");

                    b.HasIndex("ActiveTrackId");

                    b.HasIndex("CondominiumId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("EnteredAtUtc");

                    b.HasIndex("ResidentId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("MiniMercadoInteligente.Domain.Entities.ShelfInteraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<string>("CameraId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("numeric(5,4)");

                    b.Property<string>("EvidenceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("InteractionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Reconciled")
                        .HasColumnType("boolean");

                    b.Property<string>("SensorId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("TrackId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("WeightDeltaGrams")
                        .HasColumnType("numeric(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("AreaCode");

                    b.HasIndex("AreaId");

                    b.HasIndex("CameraId");

                    b.HasIndex("InteractionType");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("ProductId");

                    b.HasIndex("Reconciled");

                    b.HasIndex("SensorId");

                    b.HasIndex("SessionId");

                    b.HasIndex("TrackId");

                    b.ToTable("shelf_interactions", (string)null);
                });

            modelBuilder.Entity("MiniMercadoInteligente.Domain.Entities.TrackingSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<string>("CameraId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("numeric(5,4)");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("TrackId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AreaCode");

                    b.HasIndex("AreaId");

                    b.HasIndex("CameraId");

                    b.HasIndex("CapturedAtUtc");

                    b.HasIndex("SessionId");

                    b.HasIndex("TrackId");

                    b.ToTable("tracking_snapshots", (string)null);
                });

            modelBuilder.Entity("MiniMercadoInteligente.Domain.Entities.WeightSensor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CondominiumId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrentWeightGrams")
                        .HasColumnType("numeric(18,3)");

                    b.Property<DateTime>("LastReadingAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("LastWeightGrams")
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("SensorId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("ToleranceGrams")
                        .HasColumnType("numeric(18,3)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Active");

                    b.HasIndex("AreaCode");

                    b.HasIndex("AreaId");

                    b.HasIndex("CondominiumId");

                    b.HasIndex("SensorId")
                        .IsUnique();

                    b.ToTable("weight_sensors", (string)null);
                });

            modelBuilder.Entity("MiniMercadoInteligente.Domain.Entities.TrackingSnapshot", b =>
                {
                    b.OwnsOne("MiniMercadoInteligente.Domain.Entities.BoundingBox", "BoundingBox", b1 =>
                        {
                            b1.Property<Guid>("TrackingSnapshotId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Height")
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("bbox_height");

                            b1.Property<decimal>("Width")
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("bbox_width");

                            b1.Property<decimal>("X")
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("bbox_x");

                            b1.Property<decimal>("Y")
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("bbox_y");

                            b1.HasKey("TrackingSnapshotId");

                            b1.ToTable("tracking_snapshots");

                            b1.WithOwner()
                                .HasForeignKey("TrackingSnapshotId");
                        });

                    b.Navigation("BoundingBox")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
